### ISSUE TITLE
How to get `global-shortcut` ?

### ISSUE THREAD

**Issue by xuqiang1227** [YIXUNFE/screen-capturer#1]
error:
```
C:\workspace\screen-capturer>electron .

App threw an error during load
Error: Cannot find module 'global-shortcut'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (C:\Users\fengxj\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\workspace\screen-capturer\main.js:13:20)
    at Object.<anonymous> (C:\workspace\screen-capturer\main.js:99:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)

```
how to do ?

**Comment by xuqiang1227** [comment]
update to:
`globalShortcut = electron.globalShortcut`

thx.
